import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { ReportDocument, RenderReview } from "../contracts/index.js";
import { parseJsonFile, requiredEnv } from "../contracts/runtime.js";

const document = await parseJsonFile(requiredEnv("DOCUMENT_FILE"), ReportDocument);
const html = await readFile(resolve(process.cwd(), requiredEnv("HTML_FILE")), "utf8");
type Finding = { severity: string; message: string };
const findings: Finding[] = [];
const add = (severity: string, message: string): void => { findings.push({ severity, message }); };
if (!html.startsWith("<!doctype html>")) add("blocker", "missing doctype");
if (!html.includes("data-odyssey=\"1\"")) add("blocker", "missing Odyssey marker");
if (!html.includes("window.echarts")) add("blocker", "embedded ECharts runtime is missing");
const visible = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "");
if (visible.includes("undefined") || visible.includes("[object Object]")) add("blocker", "raw runtime value leaked into visible HTML");
const metricValues = [...visible.matchAll(/data-metric-value="([^"]*)"/g)].map((match) => (match[1] ?? "").trim());
for (const value of metricValues) if (["", "—", "undefined", "null", "NaN"].includes(value)) add("blocker", `invalid rendered metric value: ${value || "empty"}`);
const expectedMetricCount = document.elements.flatMap((entry) => entry.blocks).filter((block) => block.type === "metric-strip").reduce((sum, block) => sum + block.metrics.length, 0);
if (metricValues.length !== expectedMetricCount) add("blocker", `rendered metric count ${metricValues.length} does not match expected ${expectedMetricCount}`);
const ids = [...visible.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1] ?? "");
const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
if (duplicateIds.length) add("blocker", `duplicate DOM ids: ${[...new Set(duplicateIds)].join(", ")}`);
for (const section of document.sections) if (!ids.includes(`section-${section.sectionId}`)) add("blocker", `missing section ${section.sectionId}`);
for (const entry of document.elements) for (const block of entry.blocks) if (!ids.includes(`block-${block.id}`)) add("blocker", `missing block ${block.id}`);
if (!html.includes("class=\"re-sources\"")) add("blocker", "source list missing");
const review = RenderReview.parse({ pass: !findings.some((finding) => finding.severity === "blocker"), findings });
const outputPath = resolve(process.cwd(), requiredEnv("OUTPUT_PATH"));
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${JSON.stringify(review, null, 2)}\n`);
console.log(JSON.stringify({ type: "RENDER_VALIDATED", output: { artifactPath: process.env.OUTPUT_PATH, pass: review.pass, findings: findings.length } }));
if (!review.pass) process.exit(1);
